language: node_js

node_js:
  - "10.16.0"

notifications:
  email: false

script: gulp build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
branch: master
target-branch: gh-pages
skip_cleanup: true